### ISSUE TITLE
submission status is not being updated in the ingest endpoint

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwasdepo-ingest-service#19]
In the sandbox environment, after a successful submission the deposition sync did not pick up the submission so it did not materialise in the curation database.
Checking the ingest endpoint (/ingest/v1/publications/33409738), the status of the publication is "UNDER_SUBMISSION". This status is contrary to what is seen in the submissions page (/gwas/deposition/submissions) where the submission for that publication is "SUBMITTED". I think the status in the ingest endpoint should be "SUBMITTED".

**Comment by sajo-ebi** [comment]
Have discussed with James , this is working as expected , the confusion was between Submission & Publication status. The UI is displaying Submission status which is as per expectation
